services:
  - type: web
    name: flowpay
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: NOWPAYMENTS_IPN_SECRET
        sync: false
      - key: APP_BASE_URL
        sync: false
